In [1]:
import pandas as pd
import numpy as np

In [2]:
from azureml import Workspace
ws = Workspace(
    workspace_id='556d475f8b30495db749adc7d9379947',
    authorization_token='5a9f262ff3ab4807801d0dcad7c68e4c',
    endpoint='https://studioapi.azureml.net'
)
ds = ws.datasets['hour.csv']
df = ds.to_dataframe()

In [3]:
df.head()

,instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0,3,13,16
1,2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.80,0,8,32,40
2,3,2011-01-01,1,0,1,2,0,6,0,1,0.22,0.2727,0.80,0,5,27,32
3,4,2011-01-01,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,0,3,10,13
4,5,2011-01-01,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,0,0,1,1

In [4]:
df = df.groupby("dteday")

In [7]:
df["holiday"].agg(lambda x: set(list(x)))

dteday
2011-01-01    set([0])
2011-01-02    set([0])
2011-01-03    set([0])
2011-01-04    set([0])
2011-01-05    set([0])
2011-01-06    set([0])
2011-01-07    set([0])
2011-01-08    set([0])
2011-01-09    set([0])
2011-01-10    set([0])
2011-01-11    set([0])
2011-01-12    set([0])
2011-01-13    set([0])
2011-01-14    set([0])
2011-01-15    set([0])
...
2012-12-17    set([0])
2012-12-18    set([0])
2012-12-19    set([0])
2012-12-20    set([0])
2012-12-21    set([0])
2012-12-22    set([0])
2012-12-23    set([0])
2012-12-24    set([0])
2012-12-25    set([1])
2012-12-26    set([0])
2012-12-27    set([0])
2012-12-28    set([0])
2012-12-29    set([0])
2012-12-30    set([0])
2012-12-31    set([0])
Name: holiday, Length: 731, dtype: object