Missing data can be presented a few different ways.

In Python, we have the None keyword and type, which indicates no value.

Pandas uses NaN, which stands for "not a number", to indicate a missing value.

We can also call NaN a null value.

In [1]:
import pandas as pd
import numpy as np

In [2]:
play = pd.read_csv("C:\\Users\\Antonio\\Documents\\MEGA\\script\\python\\dati\\pbp-2015.csv")

In [3]:
play.columns

Index(['GameId', 'GameDate', 'Quarter', 'Minute', 'Second', 'OffenseTeam',
       'DefenseTeam', 'Down', 'ToGo', 'YardLine', 'Unnamed: 10',
       'SeriesFirstDown', 'Unnamed: 12', 'NextScore', 'Description', 'TeamWin',
       'Unnamed: 16', 'Unnamed: 17', 'SeasonYear', 'Yards', 'Formation',
       'PlayType', 'IsRush', 'IsPass', 'IsIncomplete', 'IsTouchdown',
       'PassType', 'IsSack', 'IsChallenge', 'IsChallengeReversed',
       'Challenger', 'IsMeasurement', 'IsInterception', 'IsFumble',
       'IsPenalty', 'IsTwoPointConversion', 'IsTwoPointConversionSuccessful',
       'RushDirection', 'YardLineFixed', 'YardLineDirection',
       'IsPenaltyAccepted', 'PenaltyTeam', 'IsNoPlay', 'PenaltyType',
       'PenaltyYards'],
      dtype='object')

To see the number of null value we use the method pd.isnull() that returns a boolean vector and then we sum this vector to obtain the number of missing values.

In [5]:
sum(pd.isnull(play["Formation"]))

706

Luckily, missing data is so common that Pandas automatically filters for it with some methods.

We can use the .mean() method to compute the mean, and it will automatically remove missing values.

In [10]:
play["GameId"].mean()

2015163920.1374981

In [4]:
play["OffenseTeam_null"] = pd.isnull(play["OffenseTeam"])

In [5]:
play["OffenseTeam_null"]

0         True
1         True
2         True
3         True
4         True
5        False
6        False
7        False
8        False
9         True
10       False
11       False
12        True
13       False
14        True
15       False
16       False
17        True
18       False
19        True
20       False
21        True
22       False
23       False
24       False
25       False
26       False
27       False
28        True
29       False
         ...
46247    False
46248    False
46249    False
46250    False
46251    False
46252    False
46253    False
46254    False
46255    False
46256    False
46257    False
46258    False
46259    False
46260    False
46261    False
46262    False
46263    False
46264    False
46265    False
46266    False
46267    False
46268    False
46269    False
46270    False
46271    False
46272    False
46273    False
46274    False
46275    False
46276    False
Name: OffenseTeam_null, dtype: bool

In [6]:
selection = play["OffenseTeam_null"] == False

In [7]:
play.loc[selection]

,GameId,GameDate,Quarter,Minute,Second,OffenseTeam,DefenseTeam,Down,ToGo,YardLine,...,IsTwoPointConversionSuccessful,RushDirection,YardLineFixed,YardLineDirection,IsPenaltyAccepted,PenaltyTeam,IsNoPlay,PenaltyType,PenaltyYards,OffenseTeam_null
5,2015091303,2015-09-13,2,9,48,WAS,MIA,2,2,20,...,0,LEFT TACKLE,20,OWN,0,NaN,0,NaN,0,False
6,2015091303,2015-09-13,2,9,13,WAS,MIA,1,10,24,...,0,NaN,24,OWN,0,NaN,0,NaN,0,False
7,2015091303,2015-09-13,4,2,33,WAS,MIA,2,11,76,...,0,NaN,24,OPP,0,NaN,0,NaN,0,False
8,2015091304,2015-09-13,1,4,57,BUF,IND,2,20,37,...,0,NaN,37,OWN,0,NaN,0,NaN,0,False
10,2015091304,2015-09-13,3,14,4,BUF,IND,1,10,68,...,0,NaN,32,OPP,0,NaN,0,NaN,0,False
11,2015091304,2015-09-13,3,13,27,BUF,IND,2,7,71,...,0,LEFT GUARD,29,OPP,0,NaN,0,NaN,0,False
13,2015091304,2015-09-13,4,13,33,BUF,IND,4,17,13,...,0,NaN,13,OWN,0,NaN,0,NaN,0,False
15,2015091305,2015-09-13,1,8,20,CLE,NYJ,3,1,28,...,0,NaN,28,OWN,0,NaN,0,NaN,0,False
16,2015091305,2015-09-13,1,7,26,CLE,NYJ,2,9,40,...,0,CENTER,40,OWN,0,NaN,0,NaN,0,False
18,2015091305,2015-09-13,2,2,0,NYJ,CLE,2,2,47,...,0,NaN,47,OWN,0,NaN,0,NaN,0,False
20,2015091305,2015-09-13,3,10,52,CLE,NYJ,3,7,37,...,0,NaN,37,OWN,0,NaN,0,NaN,0,False
22,2015091306,2015-09-13,3,4,49,KC,HOU,1,10,35,...,0,NaN,35,OWN,0,NaN,0,NaN,0,False
23,2015091306,2015-09-13,3,4,42,KC,HOU,2,10,35,...,0,NaN,35,OWN,0,NaN,0,NaN,0,False
24,2015091306,2015-09-13,4,3,26,KC,HOU,2,6,24,...,0,NaN,24,OWN,0,NaN,0,NaN,0,False
25,2015091306,2015-09-13,4,1,22,KC,HOU,1,10,50,...,0,NaN,50,OPP,0,NaN,0,NaN,0,False
26,2015091307,2015-09-13,1,7,20,NO,ARI,2,1,41,...,0,LEFT TACKLE,41,OWN,0,NaN,0,NaN,0,False
27,2015091307,2015-09-13,3,9,2,NO,ARI,1,10,43,...,0,CENTER,43,OWN,1,NO,1,OFFENSIVE HOLDING,10,False
29,2015091308,2015-09-13,2,5,2,SD,DET,0,0,35,...,0,NaN,35,OWN,0,NaN,0,NaN,0,False
30,2015091308,2015-09-13,4,14,28,SD,DET,2,7,50,...,0,NaN,50,OPP,0,NaN,0,NaN,0,False
32,2015091309,2015-09-13,4,14,12,BAL,DEN,2,10,35,...,0,NaN,35,OWN,0,NaN,0,NaN,0,False
34,2015091310,2015-09-13,2,13,41,OAK,CIN,4,6,47,...,0,NaN,47,OWN,0,NaN,0,NaN,0,False
35,2015091310,2015-09-13,3,7,50,CIN,OAK,1,10,15,...,0,NaN,15,OWN,1,OAK,1,DEFENSIVE HOLDING,5,False
36,2015091310,2015-09-13,3,0,47,OAK,CIN,2,6,32,...,0,NaN,32,OWN,0,NaN,0,NaN,0,False
37,2015091311,2015-09-13,1,10,16,TEN,TB,1,10,37,...,0,LEFT GUARD,37,OWN,0,NaN,0,NaN,0,False
38,2015091311,2015-09-13,1,0,41,TB,TEN,2,7,93,...,0,NaN,7,OPP,0,NaN,0,NaN,0,False
39,2015091311,2015-09-13,2,6,39,TEN,TB,2,9,73,...,0,RIGHT GUARD,27,OPP,0,NaN,0,NaN,0,False
40,2015091311,2015-09-13,2,0,48,TB,TEN,1,10,20,...,0,NaN,20,OWN,0,NaN,0,NaN,0,False
41,2015091311,2015-09-13,4,14,21,TEN,TB,1,15,60,...,0,LEFT GUARD,40,OPP,0,NaN,0,NaN,0,False
42,2015091311,2015-09-13,4,12,36,TB,TEN,1,10,28,...,0,LEFT TACKLE,28,OWN,0,NaN,0,NaN,0,False
43,2015091311,2015-09-13,4,2,12,TEN,TB,1,10,16,...,0,NaN,16,OWN,0,NaN,0,NaN,0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46247,2016010315,2016-01-03,2,11,29,STL,SF,3,4,64,...,0,NaN,36,OPP,0,NaN,0,NaN,0,False
46248,2016010315,2016-01-03,2,2,48,STL,SF,4,3,86,...,0,NaN,14,OPP,0,NaN,0,NaN,0,False
46249,2016010315,2016-01-03,3,11,0,SF,STL,1,10,86,...,0,CENTER,14,OPP,0,NaN,0,NaN,0,False
46250,2016010315,2016-01-03,3,10,25,SF,STL,2,11,85,...,0,NaN,15,OPP,0,NaN,0,NaN,0,False
46251,2016010315,2016-01-03,3,10,20,SF,STL,3,11,85,...,0,NaN,15,OPP,0,NaN,0,NaN,0,False
46252,2016010315,2016-01-03,3,9,41,SF,STL,4,6,90,...,0,NaN,10,OPP,0,NaN,0,NaN,0,False
46253,2016010315,2016-01-03,3,5,4,STL,SF,1,10,57,...,0,CENTER,43,OPP,0,NaN,0,NaN,0,False
46254,2016010315,2016-01-03,3,1,18,STL,SF,4,13,66,...,0,NaN,34,OPP,0,NaN,0,NaN,0,False
46255,2016010315,2016-01-03,3,0,42,SF,STL,2,1,51,...,0,RIGHT TACKLE,49,OPP,0,NaN,0,NaN,0,False
46256,2016010315,2016-01-03,4,15,0,SF,STL,1,10,52,...,0,NaN,48,OPP,0,NaN,0,NaN,0,False
46257,2016010315,2016-01-03,4,14,38,SF,STL,2,2,60,...,0,CENTER,40,OPP,1,SF,1,OFFENSIVE HOLDING,10,False
46258,2016010315,2016-01-03,4,14,17,SF,STL,2,12,50,...,0,NaN,50,OPP,0,NaN,0,NaN,0,False
46259,2016010315,2016-01-03,4,11,20,STL,SF,2,4,57,...,0,LEFT TACKLE,43,OPP,0,NaN,0,NaN,0,False
46260,2016010315,2016-01-03,4,10,38,STL,SF,3,2,59,...,0,NaN,41,OPP,0,NaN,0,NaN,0,False
46261,2016010315,2016-01-03,4,10,35,STL,SF,4,2,59,...,0,NaN,41,OPP,1,STL,1,DELAY OF GAME,5,False
46262,2016010315,2016-01-03,4,10,31,STL,SF,4,7,54,...,0,NaN,46,OPP,0,NaN,0,NaN,0,False
46263,2016010315,2016-01-03,4,5,16,SF,STL,2,3,90,...,0,CENTER,10,OPP,0,NaN,0,NaN,0,False
46264,2016010315,2016-01-03,4,4,43,SF,STL,3,1,92,...,0,NaN,8,OPP,1,STL,0,UNNECESSARY ROUGHNESS,0,False
46265,2016010315,2016-01-03,4,4,33,SF,STL,4,13,80,...,0,NaN,20,OPP,0,NaN,0,NaN,0,False
46266,2016010315,2016-01-03,4,1,49,SF,STL,2,10,57,...,0,RIGHT END,43,OPP,0,NaN,0,NaN,0,False
46267,2016010315,2016-01-03,4,1,43,SF,STL,3,4,63,...,0,NaN,37,OPP,0,NaN,0,NaN,0,False
46268,2016010315,2016-01-03,4,1,39,SF,STL,4,4,63,...,0,NaN,37,OPP,0,NaN,0,NaN,0,False
46269,2016010315,2016-01-03,5,8,31,STL,SF,1,10,58,...,0,CENTER,42,OPP,0,NaN,0,NaN,0,False
46270,2016010315,2016-01-03,5,7,49,STL,SF,2,12,56,...,0,NaN,44,OPP,0,NaN,0,NaN,0,False
46271,2016010315,2016-01-03,5,7,7,STL,SF,1,10,69,...,0,RIGHT GUARD,31,OPP,0,NaN,0,NaN,0,False
46272,2016010315,2016-01-03,5,6,23,STL,SF,2,6,73,...,0,RIGHT TACKLE,27,OPP,0,NaN,0,NaN,0,False
46273,2016010315,2016-01-03,5,5,40,STL,SF,3,9,70,...,0,CENTER,30,OPP,0,NaN,0,NaN,0,False
46274,2016010315,2016-01-03,5,5,0,STL,SF,4,9,70,...,0,NaN,30,OPP,0,NaN,0,NaN,0,False
46275,2016010315,2016-01-03,5,4,14,SF,STL,2,10,62,...,0,NaN,38,OPP,0,NaN,0,NaN,0,False
46276,2016010315,2016-01-03,5,3,31,SF,STL,1,5,95,...,0,NaN,5,OPP,0,NaN,0,NaN,0,False

In order to see the mean in an attribute for different values of another categorical attribute we use the pivot comand of pandas:

In [8]:
game_id = play.pivot_table(index="IsPass", values="GameId", aggfunc = np.mean)

In [9]:
print(game_id)

IsPass
0    2015164324
1    2015163357
Name: GameId, dtype: int64

Pivot table with more than one values:

In [10]:
play.pivot_table(index="IsPass", values=["GameId", "Yards"], aggfunc=np.mean)

              GameId     Yards
IsPass
0       2.015164e+09  1.843120
1       2.015163e+09  7.497313

We looked at how to remove missing values in a vector of data, but how about in a matrix?

We can use the dropna method on Pandas dataframes to do this.

Using the method will drop any rows that contain missing values.

In [18]:
new_play = play.dropna(subset = ["GameDate", "OffenseTeam"])
new_play.head()

,GameId,GameDate,Quarter,Minute,Second,OffenseTeam,DefenseTeam,Down,ToGo,YardLine,...,IsTwoPointConversionSuccessful,RushDirection,YardLineFixed,YardLineDirection,IsPenaltyAccepted,PenaltyTeam,IsNoPlay,PenaltyType,PenaltyYards,OffenseTeam_null
5,2015091303,2015-09-13,2,9,48,WAS,MIA,2,2,20,...,0,LEFT TACKLE,20,OWN,0,NaN,0,NaN,0,False
6,2015091303,2015-09-13,2,9,13,WAS,MIA,1,10,24,...,0,NaN,24,OWN,0,NaN,0,NaN,0,False
7,2015091303,2015-09-13,4,2,33,WAS,MIA,2,11,76,...,0,NaN,24,OPP,0,NaN,0,NaN,0,False
8,2015091304,2015-09-13,1,4,57,BUF,IND,2,20,37,...,0,NaN,37,OWN,0,NaN,0,NaN,0,False
10,2015091304,2015-09-13,3,14,4,BUF,IND,1,10,68,...,0,NaN,32,OPP,0,NaN,0,NaN,0,False

All the rows has at least a missing value, we try a different approach with a subset defined:

In [21]:
new_play = play.dropna(subset = ['GameId', 'GameDate', 'Quarter'])
new_play.head()

,GameId,GameDate,Quarter,Minute,Second,OffenseTeam,DefenseTeam,Down,ToGo,YardLine,...,IsTwoPointConversion,IsTwoPointConversionSuccessful,RushDirection,YardLineFixed,YardLineDirection,IsPenaltyAccepted,PenaltyTeam,IsNoPlay,PenaltyType,PenaltyYards
0,2015091000,2015-09-10,2,2,0,NaN,PIT,0,0,0,...,0,0,NaN,0,OWN,0,NaN,0,NaN,0
1,2015091300,2015-09-13,3,4,50,NaN,GB,0,0,0,...,0,0,NaN,0,OWN,0,NaN,0,NaN,0
2,2015091300,2015-09-13,4,0,0,NaN,GB,0,0,0,...,0,0,NaN,0,OWN,0,NaN,0,NaN,0
3,2015091301,2015-09-13,2,2,0,NaN,SEA,0,0,0,...,0,0,NaN,0,OWN,0,NaN,0,NaN,0
4,2015091302,2015-09-13,1,0,0,NaN,CAR,0,0,0,...,0,0,NaN,0,OWN,0,NaN,0,NaN,0

In order to select row, column we have to use the method .iloc:

In [23]:
new_play.iloc[3,:]

GameId                                    2015091301
GameDate                                  2015-09-13
Quarter                                            2
Minute                                             2
Second                                             0
OffenseTeam                                      NaN
DefenseTeam                                      SEA
Down                                               0
ToGo                                               0
YardLine                                           0
Unnamed: 10                                      NaN
SeriesFirstDown                                    1
Unnamed: 12                                      NaN
NextScore                                          0
Description                       TWO-MINUTE WARNING
TeamWin                                            0
Unnamed: 16                                      NaN
Unnamed: 17                                      NaN
SeasonYear                                      2015
Yards                                              0
Formation                               UNDER CENTER
PlayType                                         NaN
IsRush                                             0
IsPass                                             0
IsIncomplete                                       0
IsTouchdown                                        0
PassType                                         NaN
IsSack                                             0
IsChallenge                                        0
IsChallengeReversed                                0
Challenger                                       NaN
IsMeasurement                                      0
IsInterception                                     0
IsFumble                                           0
IsPenalty                                          0
IsTwoPointConversion                               0
IsTwoPointConversionSuccessful                     0
RushDirection                                    NaN
YardLineFixed                                      0
YardLineDirection                                OWN
IsPenaltyAccepted                                  0
PenaltyTeam                                      NaN
IsNoPlay                                           0
PenaltyType                                      NaN
PenaltyYards                                       0
Name: 3, dtype: object

Sometimes it is useful to reindex, and make new indices starting from 0, when we select a subset of the initial dataset. To do this, we can use the reset_index() method.

In [19]:
play.dropna(subset = ["OffenseTeam"]).reset_index(drop = True)

,GameId,GameDate,Quarter,Minute,Second,OffenseTeam,DefenseTeam,Down,ToGo,YardLine,...,IsTwoPointConversionSuccessful,RushDirection,YardLineFixed,YardLineDirection,IsPenaltyAccepted,PenaltyTeam,IsNoPlay,PenaltyType,PenaltyYards,OffenseTeam_null
0,2015091303,2015-09-13,2,9,48,WAS,MIA,2,2,20,...,0,LEFT TACKLE,20,OWN,0,NaN,0,NaN,0,False
1,2015091303,2015-09-13,2,9,13,WAS,MIA,1,10,24,...,0,NaN,24,OWN,0,NaN,0,NaN,0,False
2,2015091303,2015-09-13,4,2,33,WAS,MIA,2,11,76,...,0,NaN,24,OPP,0,NaN,0,NaN,0,False
3,2015091304,2015-09-13,1,4,57,BUF,IND,2,20,37,...,0,NaN,37,OWN,0,NaN,0,NaN,0,False
4,2015091304,2015-09-13,3,14,4,BUF,IND,1,10,68,...,0,NaN,32,OPP,0,NaN,0,NaN,0,False
5,2015091304,2015-09-13,3,13,27,BUF,IND,2,7,71,...,0,LEFT GUARD,29,OPP,0,NaN,0,NaN,0,False
6,2015091304,2015-09-13,4,13,33,BUF,IND,4,17,13,...,0,NaN,13,OWN,0,NaN,0,NaN,0,False
7,2015091305,2015-09-13,1,8,20,CLE,NYJ,3,1,28,...,0,NaN,28,OWN,0,NaN,0,NaN,0,False
8,2015091305,2015-09-13,1,7,26,CLE,NYJ,2,9,40,...,0,CENTER,40,OWN,0,NaN,0,NaN,0,False
9,2015091305,2015-09-13,2,2,0,NYJ,CLE,2,2,47,...,0,NaN,47,OWN,0,NaN,0,NaN,0,False
10,2015091305,2015-09-13,3,10,52,CLE,NYJ,3,7,37,...,0,NaN,37,OWN,0,NaN,0,NaN,0,False
11,2015091306,2015-09-13,3,4,49,KC,HOU,1,10,35,...,0,NaN,35,OWN,0,NaN,0,NaN,0,False
12,2015091306,2015-09-13,3,4,42,KC,HOU,2,10,35,...,0,NaN,35,OWN,0,NaN,0,NaN,0,False
13,2015091306,2015-09-13,4,3,26,KC,HOU,2,6,24,...,0,NaN,24,OWN,0,NaN,0,NaN,0,False
14,2015091306,2015-09-13,4,1,22,KC,HOU,1,10,50,...,0,NaN,50,OPP,0,NaN,0,NaN,0,False
15,2015091307,2015-09-13,1,7,20,NO,ARI,2,1,41,...,0,LEFT TACKLE,41,OWN,0,NaN,0,NaN,0,False
16,2015091307,2015-09-13,3,9,2,NO,ARI,1,10,43,...,0,CENTER,43,OWN,1,NO,1,OFFENSIVE HOLDING,10,False
17,2015091308,2015-09-13,2,5,2,SD,DET,0,0,35,...,0,NaN,35,OWN,0,NaN,0,NaN,0,False
18,2015091308,2015-09-13,4,14,28,SD,DET,2,7,50,...,0,NaN,50,OPP,0,NaN,0,NaN,0,False
19,2015091309,2015-09-13,4,14,12,BAL,DEN,2,10,35,...,0,NaN,35,OWN,0,NaN,0,NaN,0,False
20,2015091310,2015-09-13,2,13,41,OAK,CIN,4,6,47,...,0,NaN,47,OWN,0,NaN,0,NaN,0,False
21,2015091310,2015-09-13,3,7,50,CIN,OAK,1,10,15,...,0,NaN,15,OWN,1,OAK,1,DEFENSIVE HOLDING,5,False
22,2015091310,2015-09-13,3,0,47,OAK,CIN,2,6,32,...,0,NaN,32,OWN,0,NaN,0,NaN,0,False
23,2015091311,2015-09-13,1,10,16,TEN,TB,1,10,37,...,0,LEFT GUARD,37,OWN,0,NaN,0,NaN,0,False
24,2015091311,2015-09-13,1,0,41,TB,TEN,2,7,93,...,0,NaN,7,OPP,0,NaN,0,NaN,0,False
25,2015091311,2015-09-13,2,6,39,TEN,TB,2,9,73,...,0,RIGHT GUARD,27,OPP,0,NaN,0,NaN,0,False
26,2015091311,2015-09-13,2,0,48,TB,TEN,1,10,20,...,0,NaN,20,OWN,0,NaN,0,NaN,0,False
27,2015091311,2015-09-13,4,14,21,TEN,TB,1,15,60,...,0,LEFT GUARD,40,OPP,0,NaN,0,NaN,0,False
28,2015091311,2015-09-13,4,12,36,TB,TEN,1,10,28,...,0,LEFT TACKLE,28,OWN,0,NaN,0,NaN,0,False
29,2015091311,2015-09-13,4,2,12,TEN,TB,1,10,16,...,0,NaN,16,OWN,0,NaN,0,NaN,0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42943,2016010315,2016-01-03,2,11,29,STL,SF,3,4,64,...,0,NaN,36,OPP,0,NaN,0,NaN,0,False
42944,2016010315,2016-01-03,2,2,48,STL,SF,4,3,86,...,0,NaN,14,OPP,0,NaN,0,NaN,0,False
42945,2016010315,2016-01-03,3,11,0,SF,STL,1,10,86,...,0,CENTER,14,OPP,0,NaN,0,NaN,0,False
42946,2016010315,2016-01-03,3,10,25,SF,STL,2,11,85,...,0,NaN,15,OPP,0,NaN,0,NaN,0,False
42947,2016010315,2016-01-03,3,10,20,SF,STL,3,11,85,...,0,NaN,15,OPP,0,NaN,0,NaN,0,False
42948,2016010315,2016-01-03,3,9,41,SF,STL,4,6,90,...,0,NaN,10,OPP,0,NaN,0,NaN,0,False
42949,2016010315,2016-01-03,3,5,4,STL,SF,1,10,57,...,0,CENTER,43,OPP,0,NaN,0,NaN,0,False
42950,2016010315,2016-01-03,3,1,18,STL,SF,4,13,66,...,0,NaN,34,OPP,0,NaN,0,NaN,0,False
42951,2016010315,2016-01-03,3,0,42,SF,STL,2,1,51,...,0,RIGHT TACKLE,49,OPP,0,NaN,0,NaN,0,False
42952,2016010315,2016-01-03,4,15,0,SF,STL,1,10,52,...,0,NaN,48,OPP,0,NaN,0,NaN,0,False
42953,2016010315,2016-01-03,4,14,38,SF,STL,2,2,60,...,0,CENTER,40,OPP,1,SF,1,OFFENSIVE HOLDING,10,False
42954,2016010315,2016-01-03,4,14,17,SF,STL,2,12,50,...,0,NaN,50,OPP,0,NaN,0,NaN,0,False
42955,2016010315,2016-01-03,4,11,20,STL,SF,2,4,57,...,0,LEFT TACKLE,43,OPP,0,NaN,0,NaN,0,False
42956,2016010315,2016-01-03,4,10,38,STL,SF,3,2,59,...,0,NaN,41,OPP,0,NaN,0,NaN,0,False
42957,2016010315,2016-01-03,4,10,35,STL,SF,4,2,59,...,0,NaN,41,OPP,1,STL,1,DELAY OF GAME,5,False
42958,2016010315,2016-01-03,4,10,31,STL,SF,4,7,54,...,0,NaN,46,OPP,0,NaN,0,NaN,0,False
42959,2016010315,2016-01-03,4,5,16,SF,STL,2,3,90,...,0,CENTER,10,OPP,0,NaN,0,NaN,0,False
42960,2016010315,2016-01-03,4,4,43,SF,STL,3,1,92,...,0,NaN,8,OPP,1,STL,0,UNNECESSARY ROUGHNESS,0,False
42961,2016010315,2016-01-03,4,4,33,SF,STL,4,13,80,...,0,NaN,20,OPP,0,NaN,0,NaN,0,False
42962,2016010315,2016-01-03,4,1,49,SF,STL,2,10,57,...,0,RIGHT END,43,OPP,0,NaN,0,NaN,0,False
42963,2016010315,2016-01-03,4,1,43,SF,STL,3,4,63,...,0,NaN,37,OPP,0,NaN,0,NaN,0,False
42964,2016010315,2016-01-03,4,1,39,SF,STL,4,4,63,...,0,NaN,37,OPP,0,NaN,0,NaN,0,False
42965,2016010315,2016-01-03,5,8,31,STL,SF,1,10,58,...,0,CENTER,42,OPP,0,NaN,0,NaN,0,False
42966,2016010315,2016-01-03,5,7,49,STL,SF,2,12,56,...,0,NaN,44,OPP,0,NaN,0,NaN,0,False
42967,2016010315,2016-01-03,5,7,7,STL,SF,1,10,69,...,0,RIGHT GUARD,31,OPP,0,NaN,0,NaN,0,False
42968,2016010315,2016-01-03,5,6,23,STL,SF,2,6,73,...,0,RIGHT TACKLE,27,OPP,0,NaN,0,NaN,0,False
42969,2016010315,2016-01-03,5,5,40,STL,SF,3,9,70,...,0,CENTER,30,OPP,0,NaN,0,NaN,0,False
42970,2016010315,2016-01-03,5,5,0,STL,SF,4,9,70,...,0,NaN,30,OPP,0,NaN,0,NaN,0,False
42971,2016010315,2016-01-03,5,4,14,SF,STL,2,10,62,...,0,NaN,38,OPP,0,NaN,0,NaN,0,False
42972,2016010315,2016-01-03,5,3,31,SF,STL,1,5,95,...,0,NaN,5,OPP,0,NaN,0,NaN,0,False

In [20]:
play.dropna(subset = ["OffenseTeam"])

,GameId,GameDate,Quarter,Minute,Second,OffenseTeam,DefenseTeam,Down,ToGo,YardLine,...,IsTwoPointConversionSuccessful,RushDirection,YardLineFixed,YardLineDirection,IsPenaltyAccepted,PenaltyTeam,IsNoPlay,PenaltyType,PenaltyYards,OffenseTeam_null
5,2015091303,2015-09-13,2,9,48,WAS,MIA,2,2,20,...,0,LEFT TACKLE,20,OWN,0,NaN,0,NaN,0,False
6,2015091303,2015-09-13,2,9,13,WAS,MIA,1,10,24,...,0,NaN,24,OWN,0,NaN,0,NaN,0,False
7,2015091303,2015-09-13,4,2,33,WAS,MIA,2,11,76,...,0,NaN,24,OPP,0,NaN,0,NaN,0,False
8,2015091304,2015-09-13,1,4,57,BUF,IND,2,20,37,...,0,NaN,37,OWN,0,NaN,0,NaN,0,False
10,2015091304,2015-09-13,3,14,4,BUF,IND,1,10,68,...,0,NaN,32,OPP,0,NaN,0,NaN,0,False
11,2015091304,2015-09-13,3,13,27,BUF,IND,2,7,71,...,0,LEFT GUARD,29,OPP,0,NaN,0,NaN,0,False
13,2015091304,2015-09-13,4,13,33,BUF,IND,4,17,13,...,0,NaN,13,OWN,0,NaN,0,NaN,0,False
15,2015091305,2015-09-13,1,8,20,CLE,NYJ,3,1,28,...,0,NaN,28,OWN,0,NaN,0,NaN,0,False
16,2015091305,2015-09-13,1,7,26,CLE,NYJ,2,9,40,...,0,CENTER,40,OWN,0,NaN,0,NaN,0,False
18,2015091305,2015-09-13,2,2,0,NYJ,CLE,2,2,47,...,0,NaN,47,OWN,0,NaN,0,NaN,0,False
20,2015091305,2015-09-13,3,10,52,CLE,NYJ,3,7,37,...,0,NaN,37,OWN,0,NaN,0,NaN,0,False
22,2015091306,2015-09-13,3,4,49,KC,HOU,1,10,35,...,0,NaN,35,OWN,0,NaN,0,NaN,0,False
23,2015091306,2015-09-13,3,4,42,KC,HOU,2,10,35,...,0,NaN,35,OWN,0,NaN,0,NaN,0,False
24,2015091306,2015-09-13,4,3,26,KC,HOU,2,6,24,...,0,NaN,24,OWN,0,NaN,0,NaN,0,False
25,2015091306,2015-09-13,4,1,22,KC,HOU,1,10,50,...,0,NaN,50,OPP,0,NaN,0,NaN,0,False
26,2015091307,2015-09-13,1,7,20,NO,ARI,2,1,41,...,0,LEFT TACKLE,41,OWN,0,NaN,0,NaN,0,False
27,2015091307,2015-09-13,3,9,2,NO,ARI,1,10,43,...,0,CENTER,43,OWN,1,NO,1,OFFENSIVE HOLDING,10,False
29,2015091308,2015-09-13,2,5,2,SD,DET,0,0,35,...,0,NaN,35,OWN,0,NaN,0,NaN,0,False
30,2015091308,2015-09-13,4,14,28,SD,DET,2,7,50,...,0,NaN,50,OPP,0,NaN,0,NaN,0,False
32,2015091309,2015-09-13,4,14,12,BAL,DEN,2,10,35,...,0,NaN,35,OWN,0,NaN,0,NaN,0,False
34,2015091310,2015-09-13,2,13,41,OAK,CIN,4,6,47,...,0,NaN,47,OWN,0,NaN,0,NaN,0,False
35,2015091310,2015-09-13,3,7,50,CIN,OAK,1,10,15,...,0,NaN,15,OWN,1,OAK,1,DEFENSIVE HOLDING,5,False
36,2015091310,2015-09-13,3,0,47,OAK,CIN,2,6,32,...,0,NaN,32,OWN,0,NaN,0,NaN,0,False
37,2015091311,2015-09-13,1,10,16,TEN,TB,1,10,37,...,0,LEFT GUARD,37,OWN,0,NaN,0,NaN,0,False
38,2015091311,2015-09-13,1,0,41,TB,TEN,2,7,93,...,0,NaN,7,OPP,0,NaN,0,NaN,0,False
39,2015091311,2015-09-13,2,6,39,TEN,TB,2,9,73,...,0,RIGHT GUARD,27,OPP,0,NaN,0,NaN,0,False
40,2015091311,2015-09-13,2,0,48,TB,TEN,1,10,20,...,0,NaN,20,OWN,0,NaN,0,NaN,0,False
41,2015091311,2015-09-13,4,14,21,TEN,TB,1,15,60,...,0,LEFT GUARD,40,OPP,0,NaN,0,NaN,0,False
42,2015091311,2015-09-13,4,12,36,TB,TEN,1,10,28,...,0,LEFT TACKLE,28,OWN,0,NaN,0,NaN,0,False
43,2015091311,2015-09-13,4,2,12,TEN,TB,1,10,16,...,0,NaN,16,OWN,0,NaN,0,NaN,0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46247,2016010315,2016-01-03,2,11,29,STL,SF,3,4,64,...,0,NaN,36,OPP,0,NaN,0,NaN,0,False
46248,2016010315,2016-01-03,2,2,48,STL,SF,4,3,86,...,0,NaN,14,OPP,0,NaN,0,NaN,0,False
46249,2016010315,2016-01-03,3,11,0,SF,STL,1,10,86,...,0,CENTER,14,OPP,0,NaN,0,NaN,0,False
46250,2016010315,2016-01-03,3,10,25,SF,STL,2,11,85,...,0,NaN,15,OPP,0,NaN,0,NaN,0,False
46251,2016010315,2016-01-03,3,10,20,SF,STL,3,11,85,...,0,NaN,15,OPP,0,NaN,0,NaN,0,False
46252,2016010315,2016-01-03,3,9,41,SF,STL,4,6,90,...,0,NaN,10,OPP,0,NaN,0,NaN,0,False
46253,2016010315,2016-01-03,3,5,4,STL,SF,1,10,57,...,0,CENTER,43,OPP,0,NaN,0,NaN,0,False
46254,2016010315,2016-01-03,3,1,18,STL,SF,4,13,66,...,0,NaN,34,OPP,0,NaN,0,NaN,0,False
46255,2016010315,2016-01-03,3,0,42,SF,STL,2,1,51,...,0,RIGHT TACKLE,49,OPP,0,NaN,0,NaN,0,False
46256,2016010315,2016-01-03,4,15,0,SF,STL,1,10,52,...,0,NaN,48,OPP,0,NaN,0,NaN,0,False
46257,2016010315,2016-01-03,4,14,38,SF,STL,2,2,60,...,0,CENTER,40,OPP,1,SF,1,OFFENSIVE HOLDING,10,False
46258,2016010315,2016-01-03,4,14,17,SF,STL,2,12,50,...,0,NaN,50,OPP,0,NaN,0,NaN,0,False
46259,2016010315,2016-01-03,4,11,20,STL,SF,2,4,57,...,0,LEFT TACKLE,43,OPP,0,NaN,0,NaN,0,False
46260,2016010315,2016-01-03,4,10,38,STL,SF,3,2,59,...,0,NaN,41,OPP,0,NaN,0,NaN,0,False
46261,2016010315,2016-01-03,4,10,35,STL,SF,4,2,59,...,0,NaN,41,OPP,1,STL,1,DELAY OF GAME,5,False
46262,2016010315,2016-01-03,4,10,31,STL,SF,4,7,54,...,0,NaN,46,OPP,0,NaN,0,NaN,0,False
46263,2016010315,2016-01-03,4,5,16,SF,STL,2,3,90,...,0,CENTER,10,OPP,0,NaN,0,NaN,0,False
46264,2016010315,2016-01-03,4,4,43,SF,STL,3,1,92,...,0,NaN,8,OPP,1,STL,0,UNNECESSARY ROUGHNESS,0,False
46265,2016010315,2016-01-03,4,4,33,SF,STL,4,13,80,...,0,NaN,20,OPP,0,NaN,0,NaN,0,False
46266,2016010315,2016-01-03,4,1,49,SF,STL,2,10,57,...,0,RIGHT END,43,OPP,0,NaN,0,NaN,0,False
46267,2016010315,2016-01-03,4,1,43,SF,STL,3,4,63,...,0,NaN,37,OPP,0,NaN,0,NaN,0,False
46268,2016010315,2016-01-03,4,1,39,SF,STL,4,4,63,...,0,NaN,37,OPP,0,NaN,0,NaN,0,False
46269,2016010315,2016-01-03,5,8,31,STL,SF,1,10,58,...,0,CENTER,42,OPP,0,NaN,0,NaN,0,False
46270,2016010315,2016-01-03,5,7,49,STL,SF,2,12,56,...,0,NaN,44,OPP,0,NaN,0,NaN,0,False
46271,2016010315,2016-01-03,5,7,7,STL,SF,1,10,69,...,0,RIGHT GUARD,31,OPP,0,NaN,0,NaN,0,False
46272,2016010315,2016-01-03,5,6,23,STL,SF,2,6,73,...,0,RIGHT TACKLE,27,OPP,0,NaN,0,NaN,0,False
46273,2016010315,2016-01-03,5,5,40,STL,SF,3,9,70,...,0,CENTER,30,OPP,0,NaN,0,NaN,0,False
46274,2016010315,2016-01-03,5,5,0,STL,SF,4,9,70,...,0,NaN,30,OPP,0,NaN,0,NaN,0,False
46275,2016010315,2016-01-03,5,4,14,SF,STL,2,10,62,...,0,NaN,38,OPP,0,NaN,0,NaN,0,False
46276,2016010315,2016-01-03,5,3,31,SF,STL,1,5,95,...,0,NaN,5,OPP,0,NaN,0,NaN,0,False

In [22]:
def count_na(series):
    return sum(pd.isnull(series))
play.apply(count_na)

GameId                                0
GameDate                              0
Quarter                               0
Minute                                0
Second                                0
OffenseTeam                        3304
DefenseTeam                           0
Down                                  0
ToGo                                  0
YardLine                              0
Unnamed: 10                       46277
SeriesFirstDown                       0
Unnamed: 12                       46277
NextScore                             0
Description                           0
TeamWin                               0
Unnamed: 16                       46277
Unnamed: 17                       46277
SeasonYear                            0
Yards                                 0
Formation                           706
PlayType                           1498
IsRush                                0
IsPass                                0
IsIncomplete                          0
IsTouchdown                           0
PassType                          26926
IsSack                                0
IsChallenge                           0
IsChallengeReversed                   0
Challenger                        46277
IsMeasurement                         0
IsInterception                        0
IsFumble                              0
IsPenalty                             0
IsTwoPointConversion                  0
IsTwoPointConversionSuccessful        0
RushDirection                     33734
YardLineFixed                         0
YardLineDirection                     0
IsPenaltyAccepted                     0
PenaltyTeam                       42256
IsNoPlay                              0
PenaltyType                       42254
PenaltyYards                          0
OffenseTeam_null                      0
dtype: int64